// tb_fma_top.v
// Self-checking testbench: reads tb/vectors.txt (generated by
// gen_vectors.py against golden_model.py, an independent reference model)
// drives one operation per cycle into the fully-pipelined U_FMA, and
// checks dout_o against the expected result 3 cycles later (the design's
// pipeline latency: 1 register in fma_top + 2 inside fma_lane_pipe).
`include "fma_defs.vh"

module tb_fma_top;
  localparam MAXV = 2000;
  // 3 pipeline registers (PREG1 in fma_top + 2 inside fma_lane_pipe) means
  // a vector's result is valid after 3 posedges from when its inputs were
  // first stable; since each loop iteration below applies inputs *before*
  // its own posedge, that result lands during the iteration 2 cycles
  // later (cyc=2 for the vector applied at cyc=0), not 3.
  localparam LAT  = 2;

  reg clk = 0;
  reg rst_n = 0;
  always #5 clk = ~clk;

  reg [63:0]  a_i, b_i, c_i;
  reg         mixmode_i;
  reg [1:0]   pra_i, prm_i;
  reg [3:0]   ewa_i, ewm_i;
  wire [127:0] dout_o;

  fma_top dut (
      .clk_i(clk), .rst_n_i(rst_n),
      .a_i(a_i), .b_i(b_i), .c_i(c_i),
      .mixmode_i(mixmode_i), .pra_i(pra_i), .prm_i(prm_i),
      .ewa_i(ewa_i), .ewm_i(ewm_i),
      .dout_o(dout_o)
  );

  // ------------------------------------------------------------------
  // Waveform dump, scoped to the SYSTEM's top-level I/O only.
  // Enabled at compile time with +define+DUMP_WAVES (see tb/run_vcs.sh);
  // the default self-checking run leaves this out so its behaviour and
  // runtime are unchanged. By naming the DUT's ports individually,
  // $dumpvars records ONLY those signals -- the primary inputs and the
  // output -- and none of fma_top's internal pipeline nets, giving a
  // waveform whose scope is exactly the inputs and outputs of the FMA.
  `ifdef DUMP_WAVES
  initial begin
    $dumpfile("fma_io.vcd");
    $dumpvars(0, dut.clk_i, dut.rst_n_i,
                 dut.a_i, dut.b_i, dut.c_i,
                 dut.mixmode_i, dut.pra_i, dut.prm_i,
                 dut.ewa_i, dut.ewm_i,
                 dut.dout_o);
  end
  `endif

  integer n_vec;
  integer v_mixmode [0:MAXV-1];
  integer v_pra     [0:MAXV-1];
  integer v_prm     [0:MAXV-1];
  integer v_ewa     [0:MAXV-1];
  integer v_ewm     [0:MAXV-1];
  reg [63:0] v_a [0:MAXV-1];
  reg [63:0] v_b [0:MAXV-1];
  reg [63:0] v_c [0:MAXV-1];
  reg [31:0] v_exp [0:MAXV-1];

  integer fd;
  integer rc;
  reg [8*32-1:0] label_tmp;

  integer pass_count, fail_count;
  integer i, cyc, idx;

  initial begin
    fd = $fopen("vectors.txt", "r");
    if (fd == 0) begin
      $display("ERROR: could not open vectors.txt");
      $finish;
    end
    rc = $fscanf(fd, "%d\n", n_vec);
    $display("Reading %0d vectors", n_vec);
    for (i = 0; i < n_vec; i = i + 1) begin
      rc = $fscanf(fd, "%d %d %d %d %d %h %h %h %h %s\n",
                    v_mixmode[i], v_pra[i], v_prm[i], v_ewa[i], v_ewm[i],
                    v_a[i], v_b[i], v_c[i], v_exp[i], label_tmp);
      if (rc != 10) begin
        $display("ERROR: parse failure at vector %0d (rc=%0d)", i, rc);
        $finish;
      end
    end
    $fclose(fd);

    pass_count = 0;
    fail_count = 0;

    a_i = 0; b_i = 0; c_i = 0; mixmode_i = 0; pra_i = `CLS_8; prm_i = `CLS_8;
    ewa_i = 4'd4; ewm_i = 4'd4;

    @(posedge clk);
    rst_n = 1;

    for (cyc = 0; cyc < n_vec + LAT + 2; cyc = cyc + 1) begin
      // drive stage-1 inputs for this cycle
      if (cyc < n_vec) begin
        a_i = v_a[cyc]; b_i = v_b[cyc]; c_i = v_c[cyc];
        mixmode_i = v_mixmode[cyc][0];
        pra_i = v_pra[cyc][1:0];
        prm_i = v_prm[cyc][1:0];
        ewa_i = v_ewa[cyc][3:0];
        ewm_i = v_ewm[cyc][3:0];
      end else begin
        a_i = 0; b_i = 0; c_i = 0;
      end

      @(posedge clk);
      #1; // settle combinational dout_o after this edge

      // check the result issued LAT cycles ago
      if (cyc >= LAT) begin
        idx = cyc - LAT;
        if (idx < n_vec) begin
          if (dout_o[31:0] !== v_exp[idx]) begin
            fail_count = fail_count + 1;
            if (fail_count <= 40) begin
              $display("FAIL [%0d]: got=%08x exp=%08x  (mixmode=%0d pra=%0d prm=%0d ewa=%0d ewm=%0d a=%016x b=%016x c=%016x)",
                        idx, dout_o[31:0], v_exp[idx],
                        v_mixmode[idx], v_pra[idx], v_prm[idx], v_ewa[idx], v_ewm[idx],
                        v_a[idx], v_b[idx], v_c[idx]);
            end
          end else begin
            pass_count = pass_count + 1;
          end
        end
      end
    end

    $display("---------------------------------------------");
    $display("TOTAL: %0d   PASS: %0d   FAIL: %0d", n_vec, pass_count, fail_count);
    if (fail_count == 0) $display("RESULT: ALL PASS");
    else $display("RESULT: FAILURES PRESENT");
    $finish;
  end

  initial begin
    #200000;
    $display("TIMEOUT");
    $finish;
  end
endmodule
