// tb_fma_top.v
// Self-checking system testbench for U_FMA (fma_top).
//
// Reads tb/vectors.txt (generated by gen_vectors.py from golden_model.py,
// an independent exact-arithmetic reference), drives one operation per
// clock into the fully-pipelined FMA (back-to-back, no bubbles, the mode/
// format changing from one cycle to the next), and compares dout_o with the
// expected result when that operation comes out of the pipeline.
//
// Outputs:
//   console          : first 40 mismatches + TOTAL/PASS/FAIL line
//   sim_results.txt  : one line per vector "idx got_hex exp_hex P|F",
//                      read by report.py to build the human-readable report
//   waves (optional) : +define+DUMP_WAVES -> fma_waves.vcd
//                      +define+USE_SHM    -> fma_waves.shm (Cadence SimVision)
//                      containing the FMA's top-level I/O plus the decoded
//                      "view_*" signals below (operands/results as decimal
//                      numbers, the vector label, and a mismatch flag).
`include "fma_defs.vh"

module tb_fma_top;
  localparam MAXV = 20000;
  // 3 pipeline registers (PREG1 in fma_top + 2 inside fma_lane_pipe) means
  // a vector's result is valid after 3 posedges from when its inputs were
  // first stable; since each loop iteration below applies inputs *before*
  // its own posedge, that result lands during the iteration 2 cycles
  // later (cyc=2 for the vector applied at cyc=0), not 3.
  localparam LAT  = 2;
  localparam LW   = 48; // max label length (characters)

  reg clk = 0;
  reg rst_n = 0;
  always #5 clk = ~clk;

  reg [63:0]  a_i, b_i, c_i;
  reg         mixmode_i;
  reg [1:0]   pra_i, prm_i;
  reg [3:0]   ewa_i, ewm_i;
  wire [127:0] dout_o;

  fma_top dut (
      .clk_i(clk), .rst_n_i(rst_n),
      .a_i(a_i), .b_i(b_i), .c_i(c_i),
      .mixmode_i(mixmode_i), .pra_i(pra_i), .prm_i(prm_i),
      .ewa_i(ewa_i), .ewm_i(ewm_i),
      .dout_o(dout_o)
  );

  integer n_vec;
  integer v_mixmode [0:MAXV-1];
  integer v_pra     [0:MAXV-1];
  integer v_prm     [0:MAXV-1];
  integer v_ewa     [0:MAXV-1];
  integer v_ewm     [0:MAXV-1];
  reg [63:0] v_a [0:MAXV-1];
  reg [63:0] v_b [0:MAXV-1];
  reg [63:0] v_c [0:MAXV-1];
  reg [31:0] v_exp [0:MAXV-1];
  reg [8*LW-1:0] v_label [0:MAXV-1];

  integer fd, fr;
  integer rc;
  reg [8*LW-1:0] label_tmp;

  integer pass_count, fail_count;
  integer i, cyc, idx;

  // ------------------------------------------------------------------
  // Decoded "view" signals (for waveforms / live demo). Every value is
  // shown as a plain decimal number (Verilog real). Lanes that are not
  // used by the current format/mode show 0. Infinity is shown as
  // +/-1e308; NaN is shown as 0 with view_out_nan=1 (check the hex).
  //   view_in_*  : the operation being APPLIED this cycle
  //   view_out_* : the operation whose RESULT is on dout_o this cycle
  //               (applied LAT+1 clock edges earlier)
  // ------------------------------------------------------------------
  integer        view_in_idx, view_out_idx;
  reg [8*LW-1:0] view_in_label, view_out_label;
  real view_in_A0, view_in_A1, view_in_A2, view_in_A3;
  real view_in_B0, view_in_B1, view_in_B2, view_in_B3;
  real view_in_C0, view_in_C1, view_in_C2, view_in_C3;
  real view_out_got0, view_out_got1, view_out_got2, view_out_got3;
  real view_out_exp0, view_out_exp1, view_out_exp2, view_out_exp3;
  reg [31:0] view_out_got_hex, view_out_exp_hex;
  reg        view_out_nan;
  reg        view_mismatch;

  function integer total_bits;
    input [1:0] cls;
    begin
      case (cls)
        `CLS_8:  total_bits = 8;
        `CLS_16: total_bits = 16;
        `CLS_32: total_bits = 32;
        default: total_bits = 19;
      endcase
    end
  endfunction

  function integer n_lanes;
    input [1:0] cls;
    begin
      case (cls)
        `CLS_8:  n_lanes = 4;
        `CLS_16: n_lanes = 2;
        default: n_lanes = 1;
      endcase
    end
  endfunction

  // lane `ln` of a packed bus, right-justified (see fma_top.v packing)
  function [31:0] lane_bits;
    input [63:0] bus;
    input [1:0]  cls;
    input integer ln;
    begin
      case (cls)
        `CLS_8:  lane_bits = (bus >> (8 * ln)) & 32'hFF;
        `CLS_16: lane_bits = (bus >> (16 * ln)) & 32'hFFFF;
        `CLS_32: lane_bits = bus[31:0];
        default: lane_bits = bus[18:0];
      endcase
    end
  endfunction

  // decode one S/E/M value of class `cls` with `ew` exponent bits to a real
  function real fp_to_real;
    input [31:0] bits;
    input [1:0]  cls;
    input [3:0]  ew;
    integer total, m, bias, ef, k;
    reg     s;
    reg [31:0] mf;
    real    frac, sgn;
    begin
      total = total_bits(cls);
      m     = total - 1 - ew;
      bias  = (1 << (ew - 1)) - 1;
      s     = bits[total - 1];
      ef    = (bits >> m) & ((1 << ew) - 1);
      mf    = bits & ((32'h1 << m) - 1);
      frac  = mf / (2.0 ** m);
      sgn   = s ? -1.0 : 1.0;
      if (ef == (1 << ew) - 1)
        fp_to_real = (mf != 0) ? 0.0 : sgn * 1.0e308;
      else if (ef == 0)
        fp_to_real = sgn * frac * (2.0 ** (1 - bias));
      else
        fp_to_real = sgn * (1.0 + frac) * (2.0 ** (ef - bias));
    end
  endfunction

  function is_nan_bits;
    input [31:0] bits;
    input [1:0]  cls;
    input [3:0]  ew;
    integer total, m, ef;
    begin
      total = total_bits(cls);
      m     = total - 1 - ew;
      ef    = (bits >> m) & ((1 << ew) - 1);
      is_nan_bits = (ef == (1 << ew) - 1) && ((bits & ((32'h1 << m) - 1)) != 0);
    end
  endfunction

  // value of operand lane `ln` (0 if the lane is unused by this vector)
  function real in_lane;
    input integer v;     // vector index
    input integer which; // 0=A, 1=B, 2=C
    input integer ln;
    reg [1:0] cls;
    reg [3:0] ew;
    reg [63:0] bus;
    integer nl;
    begin
      if (which == 0 && v_mixmode[v] != 0) begin
        cls = v_pra[v]; ew = v_ewa[v]; nl = 1;       // single wide addend
      end else if (which == 0) begin
        cls = v_pra[v]; ew = v_ewa[v]; nl = n_lanes(cls);
      end else begin
        cls = v_prm[v]; ew = v_ewm[v]; nl = n_lanes(cls);
      end
      bus = (which == 0) ? v_a[v] : (which == 1) ? v_b[v] : v_c[v];
      in_lane = (ln < nl) ? fp_to_real(lane_bits(bus, cls, ln), cls, ew) : 0.0;
    end
  endfunction

  // value of result lane `ln` of a 32-bit packed result for vector v
  function real out_lane;
    input integer v;
    input [31:0] res;
    input integer ln;
    integer nl;
    begin
      nl = v_mixmode[v] ? 1 : n_lanes(v_pra[v]);
      out_lane = (ln < nl) ? fp_to_real(lane_bits({32'b0, res}, v_pra[v], ln), v_pra[v], v_ewa[v]) : 0.0;
    end
  endfunction

  task set_in_view;
    input integer v;
    begin
      view_in_idx = v; view_in_label = v_label[v];
      view_in_A0 = in_lane(v, 0, 0); view_in_A1 = in_lane(v, 0, 1);
      view_in_A2 = in_lane(v, 0, 2); view_in_A3 = in_lane(v, 0, 3);
      view_in_B0 = in_lane(v, 1, 0); view_in_B1 = in_lane(v, 1, 1);
      view_in_B2 = in_lane(v, 1, 2); view_in_B3 = in_lane(v, 1, 3);
      view_in_C0 = in_lane(v, 2, 0); view_in_C1 = in_lane(v, 2, 1);
      view_in_C2 = in_lane(v, 2, 2); view_in_C3 = in_lane(v, 2, 3);
    end
  endtask

  task set_out_view;
    input integer v;
    input [31:0] got;
    integer nl, ln;
    begin
      view_out_idx = v; view_out_label = v_label[v];
      view_out_got_hex = got; view_out_exp_hex = v_exp[v];
      view_out_got0 = out_lane(v, got, 0); view_out_exp0 = out_lane(v, v_exp[v], 0);
      view_out_got1 = out_lane(v, got, 1); view_out_exp1 = out_lane(v, v_exp[v], 1);
      view_out_got2 = out_lane(v, got, 2); view_out_exp2 = out_lane(v, v_exp[v], 2);
      view_out_got3 = out_lane(v, got, 3); view_out_exp3 = out_lane(v, v_exp[v], 3);
      nl = v_mixmode[v] ? 1 : n_lanes(v_pra[v]);
      view_out_nan = 1'b0;
      for (ln = 0; ln < nl; ln = ln + 1)
        if (is_nan_bits(lane_bits({32'b0, got}, v_pra[v], ln), v_pra[v], v_ewa[v]))
          view_out_nan = 1'b1;
      view_mismatch = (got !== v_exp[v]);
    end
  endtask

  // ------------------------------------------------------------------
  // Waveform dump: the testbench scope only = the FMA's top-level I/O
  // (clk, rst_n, a_i/b_i/c_i, mixmode_i, pra_i/prm_i, ewa_i/ewm_i, dout_o)
  // plus the decoded view_* signals -- none of the internal pipeline nets.
  // To capture the whole design hierarchy instead, use
  // $dumpvars(0, tb_fma_top) / $shm_probe(tb_fma_top, "AS").
  // ------------------------------------------------------------------
  `ifdef DUMP_WAVES
  initial begin
    $dumpfile("fma_waves.vcd");
    $dumpvars(1, tb_fma_top);
  end
  `endif
  `ifdef USE_SHM
  initial begin
    $shm_open("fma_waves.shm");
    $shm_probe(tb_fma_top, "A");
  end
  `endif

  initial begin
    view_in_idx = -1; view_out_idx = -1; view_in_label = "reset"; view_out_label = "reset";
    view_out_got_hex = 0; view_out_exp_hex = 0; view_out_nan = 0; view_mismatch = 0;
    view_in_A0 = 0.0; view_in_A1 = 0.0; view_in_A2 = 0.0; view_in_A3 = 0.0;
    view_in_B0 = 0.0; view_in_B1 = 0.0; view_in_B2 = 0.0; view_in_B3 = 0.0;
    view_in_C0 = 0.0; view_in_C1 = 0.0; view_in_C2 = 0.0; view_in_C3 = 0.0;
    view_out_got0 = 0.0; view_out_got1 = 0.0; view_out_got2 = 0.0; view_out_got3 = 0.0;
    view_out_exp0 = 0.0; view_out_exp1 = 0.0; view_out_exp2 = 0.0; view_out_exp3 = 0.0;

    fd = $fopen("vectors.txt", "r");
    if (fd == 0) begin
      $display("ERROR: could not open vectors.txt");
      $finish;
    end
    rc = $fscanf(fd, "%d\n", n_vec);
    if (n_vec > MAXV) begin
      $display("ERROR: %0d vectors > MAXV=%0d, raise MAXV in tb_fma_top.v", n_vec, MAXV);
      $finish;
    end
    $display("Reading %0d vectors", n_vec);
    for (i = 0; i < n_vec; i = i + 1) begin
      rc = $fscanf(fd, "%d %d %d %d %d %h %h %h %h %s\n",
                    v_mixmode[i], v_pra[i], v_prm[i], v_ewa[i], v_ewm[i],
                    v_a[i], v_b[i], v_c[i], v_exp[i], label_tmp);
      if (rc != 10) begin
        $display("ERROR: parse failure at vector %0d (rc=%0d)", i, rc);
        $finish;
      end
      v_label[i] = label_tmp;
    end
    $fclose(fd);

    fr = $fopen("sim_results.txt", "w");
    pass_count = 0;
    fail_count = 0;

    a_i = 0; b_i = 0; c_i = 0; mixmode_i = 0; pra_i = `CLS_8; prm_i = `CLS_8;
    ewa_i = 4'd4; ewm_i = 4'd4;

    @(posedge clk);
    rst_n = 1;

    for (cyc = 0; cyc < n_vec + LAT + 2; cyc = cyc + 1) begin
      // drive stage-1 inputs for this cycle
      if (cyc < n_vec) begin
        a_i = v_a[cyc]; b_i = v_b[cyc]; c_i = v_c[cyc];
        mixmode_i = v_mixmode[cyc][0];
        pra_i = v_pra[cyc][1:0];
        prm_i = v_prm[cyc][1:0];
        ewa_i = v_ewa[cyc][3:0];
        ewm_i = v_ewm[cyc][3:0];
        set_in_view(cyc);
      end else begin
        a_i = 0; b_i = 0; c_i = 0;
        view_in_idx = -1; view_in_label = "idle";
      end

      @(posedge clk);
      #1; // settle combinational dout_o after this edge

      // check the result issued LAT cycles ago
      if (cyc >= LAT) begin
        idx = cyc - LAT;
        if (idx < n_vec) begin
          set_out_view(idx, dout_o[31:0]);
          if (dout_o[31:0] !== v_exp[idx]) begin
            fail_count = fail_count + 1;
            $fdisplay(fr, "%0d %08x %08x F", idx, dout_o[31:0], v_exp[idx]);
            if (fail_count <= 40) begin
              $display("FAIL [%0d] %0s: got=%08x exp=%08x  (mixmode=%0d pra=%0d prm=%0d ewa=%0d ewm=%0d a=%016x b=%016x c=%016x)",
                        idx, v_label[idx], dout_o[31:0], v_exp[idx],
                        v_mixmode[idx], v_pra[idx], v_prm[idx], v_ewa[idx], v_ewm[idx],
                        v_a[idx], v_b[idx], v_c[idx]);
            end
          end else begin
            pass_count = pass_count + 1;
            $fdisplay(fr, "%0d %08x %08x P", idx, dout_o[31:0], v_exp[idx]);
          end
        end
      end
    end
    $fclose(fr);

    $display("---------------------------------------------");
    $display("TOTAL: %0d   PASS: %0d   FAIL: %0d", n_vec, pass_count, fail_count);
    if (fail_count == 0) $display("RESULT: ALL PASS");
    else $display("RESULT: FAILURES PRESENT");
    $finish;
  end

  initial begin
    #100000000;
    $display("TIMEOUT");
    $finish;
  end
endmodule
